[2024-07-14T04:35:19.184+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:35:19.353+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_customers.run scheduled__2024-07-04T00:00:00+00:00 [queued]>
[2024-07-14T04:35:19.449+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_customers.run scheduled__2024-07-04T00:00:00+00:00 [queued]>
[2024-07-14T04:35:19.452+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:35:19.520+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_customers.run> on 2024-07-04 00:00:00+00:00
[2024-07-14T04:35:19.555+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=19119) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:35:19.566+0000] {standard_task_runner.py:63} INFO - Started process 19146 to run task
[2024-07-14T04:35:19.565+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_customers.run', 'scheduled__2024-07-04T00:00:00+00:00', '--job-id', '1455', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpelod00n0']
[2024-07-14T04:35:19.582+0000] {standard_task_runner.py:91} INFO - Job 1455: Subtask transform.raw_customers.run
[2024-07-14T04:35:19.711+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:35:19.881+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_customers.run scheduled__2024-07-04T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:35:20.469+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_customers.run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-04T00:00:00+00:00'
[2024-07-14T04:35:20.473+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:35:20.477+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:35:20.484+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp55maggkv from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:35:20.540+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:35:20.739+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:35:20.744+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:35:20.746+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:35:20.761+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:35:20.764+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp55maggkv', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp55maggkv
[2024-07-14T04:35:20.772+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:35:20.777+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp55maggkv', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:35:20.864+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:35:36.953+0000] {subprocess.py:94} INFO - [0m04:35:36  Running with dbt=1.8.3
[2024-07-14T04:35:38.964+0000] {subprocess.py:94} INFO - [0m04:35:38  Updating lock file in file path: /tmp/tmp55maggkv/package-lock.yml
[2024-07-14T04:35:39.008+0000] {subprocess.py:94} INFO - [0m04:35:39  Installing dbt-labs/dbt_utils
[2024-07-14T04:35:39.885+0000] {subprocess.py:94} INFO - [0m04:35:39  Installed from version 0.8.6
[2024-07-14T04:35:39.889+0000] {subprocess.py:94} INFO - [0m04:35:39  Updated version available: 1.2.0
[2024-07-14T04:35:39.896+0000] {subprocess.py:94} INFO - [0m04:35:39
[2024-07-14T04:35:39.914+0000] {subprocess.py:94} INFO - [0m04:35:39  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:35:39.922+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:35:47.853+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:35:47.859+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:35:47.864+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_customers', '--project-dir', '/tmp/tmp55maggkv', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp55maggkv
[2024-07-14T04:35:47.874+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:35:47.889+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_customers', '--project-dir', '/tmp/tmp55maggkv', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:35:47.960+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:36:02.766+0000] {subprocess.py:94} INFO - [0m04:36:02  Running with dbt=1.8.3
[2024-07-14T04:36:06.748+0000] {subprocess.py:94} INFO - [0m04:36:06  Registered adapter: snowflake=1.8.3
[2024-07-14T04:36:11.455+0000] {subprocess.py:94} INFO - [0m04:36:11  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:36:11.466+0000] {subprocess.py:94} INFO - [0m04:36:11
[2024-07-14T04:36:20.041+0000] {subprocess.py:94} INFO - [0m04:36:20  Concurrency: 1 threads (target='dev')
[2024-07-14T04:36:20.047+0000] {subprocess.py:94} INFO - [0m04:36:20
[2024-07-14T04:36:20.228+0000] {subprocess.py:94} INFO - [0m04:36:20  1 of 1 START sql table model raw.raw_customers ................................. [RUN]
[2024-07-14T04:36:23.151+0000] {subprocess.py:94} INFO - [0m04:36:23  1 of 1 OK created sql table model raw.raw_customers ............................ [[32mSUCCESS 1[0m in 2.91s]
[2024-07-14T04:36:23.173+0000] {subprocess.py:94} INFO - [0m04:36:23
[2024-07-14T04:36:23.180+0000] {subprocess.py:94} INFO - [0m04:36:23  Finished running 1 table model in 0 hours 0 minutes and 11.70 seconds (11.70s).
[2024-07-14T04:36:24.248+0000] {subprocess.py:94} INFO - [0m04:36:24
[2024-07-14T04:36:24.252+0000] {subprocess.py:94} INFO - [0m04:36:24  [32mCompleted successfully[0m
[2024-07-14T04:36:24.275+0000] {subprocess.py:94} INFO - [0m04:36:24
[2024-07-14T04:36:24.299+0000] {subprocess.py:94} INFO - [0m04:36:24  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:36:31.342+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:36:31.345+0000] {local.py:254} INFO - [0m04:36:24  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:36:32.302+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:36:32.323+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:36:32.343+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.PUBLIC.customers', extra=None)]
[2024-07-14T04:36:32.363+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_customers', extra=None)]
[2024-07-14T04:36:32.365+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:36:32.831+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:36:33.054+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_customers.run, run_id=scheduled__2024-07-04T00:00:00+00:00, execution_date=20240704T000000, start_date=20240714T043519, end_date=20240714T043633
[2024-07-14T04:36:33.268+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:36:33.354+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
