[2024-07-14T04:47:45.872+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:47:46.045+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.best_employee_run scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-14T04:47:46.118+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.best_employee_run scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-14T04:47:46.119+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:47:46.190+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.best_employee_run> on 2024-07-08 00:00:00+00:00
[2024-07-14T04:47:46.227+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=21800) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:47:46.243+0000] {standard_task_runner.py:63} INFO - Started process 21827 to run task
[2024-07-14T04:47:46.235+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.best_employee_run', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '1624', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmptdkzy4bh']
[2024-07-14T04:47:46.248+0000] {standard_task_runner.py:91} INFO - Job 1624: Subtask transform.best_employee_run
[2024-07-14T04:47:46.400+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:47:46.581+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.best_employee_run scheduled__2024-07-08T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:47:47.138+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.best_employee_run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T00:00:00+00:00'
[2024-07-14T04:47:47.146+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:47:47.167+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:47:47.172+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpaqvlio3b from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:47:47.185+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:47:47.360+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:47:47.366+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:47:47.372+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:47:47.417+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:47:47.421+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpaqvlio3b', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpaqvlio3b
[2024-07-14T04:47:47.439+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:47:47.457+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpaqvlio3b', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:47:47.629+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:48:02.893+0000] {subprocess.py:94} INFO - [0m04:48:02  Running with dbt=1.8.3
[2024-07-14T04:48:04.502+0000] {subprocess.py:94} INFO - [0m04:48:04  Updating lock file in file path: /tmp/tmpaqvlio3b/package-lock.yml
[2024-07-14T04:48:04.525+0000] {subprocess.py:94} INFO - [0m04:48:04  Installing dbt-labs/dbt_utils
[2024-07-14T04:48:05.229+0000] {subprocess.py:94} INFO - [0m04:48:05  Installed from version 0.8.6
[2024-07-14T04:48:05.232+0000] {subprocess.py:94} INFO - [0m04:48:05  Updated version available: 1.2.0
[2024-07-14T04:48:05.239+0000] {subprocess.py:94} INFO - [0m04:48:05
[2024-07-14T04:48:05.242+0000] {subprocess.py:94} INFO - [0m04:48:05  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:48:05.244+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:48:08.349+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:48:08.352+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:48:08.354+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'best_employee', '--project-dir', '/tmp/tmpaqvlio3b', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpaqvlio3b
[2024-07-14T04:48:08.357+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:48:08.360+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'best_employee', '--project-dir', '/tmp/tmpaqvlio3b', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:48:08.446+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:48:22.748+0000] {subprocess.py:94} INFO - [0m04:48:22  Running with dbt=1.8.3
[2024-07-14T04:48:25.924+0000] {subprocess.py:94} INFO - [0m04:48:25  Registered adapter: snowflake=1.8.3
[2024-07-14T04:48:32.071+0000] {subprocess.py:94} INFO - [0m04:48:32  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:48:32.085+0000] {subprocess.py:94} INFO - [0m04:48:32
[2024-07-14T04:48:40.546+0000] {subprocess.py:94} INFO - [0m04:48:40  Concurrency: 1 threads (target='dev')
[2024-07-14T04:48:40.548+0000] {subprocess.py:94} INFO - [0m04:48:40
[2024-07-14T04:48:40.687+0000] {subprocess.py:94} INFO - [0m04:48:40  1 of 1 START sql table model dm.best_employee .................................. [RUN]
[2024-07-14T04:48:44.171+0000] {subprocess.py:94} INFO - [0m04:48:44  1 of 1 OK created sql table model dm.best_employee ............................. [[32mSUCCESS 1[0m in 3.47s]
[2024-07-14T04:48:44.209+0000] {subprocess.py:94} INFO - [0m04:48:44
[2024-07-14T04:48:44.213+0000] {subprocess.py:94} INFO - [0m04:48:44  Finished running 1 table model in 0 hours 0 minutes and 12.12 seconds (12.12s).
[2024-07-14T04:48:44.734+0000] {subprocess.py:94} INFO - [0m04:48:44
[2024-07-14T04:48:44.737+0000] {subprocess.py:94} INFO - [0m04:48:44  [32mCompleted successfully[0m
[2024-07-14T04:48:44.741+0000] {subprocess.py:94} INFO - [0m04:48:44
[2024-07-14T04:48:44.745+0000] {subprocess.py:94} INFO - [0m04:48:44  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:48:46.787+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:48:46.789+0000] {local.py:254} INFO - [0m04:48:44  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:48:47.533+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:48:47.568+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:48:47.669+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_employees', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.fact_order_details', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.fact_orders', extra=None)]
[2024-07-14T04:48:47.677+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dm.best_employee', extra=None)]
[2024-07-14T04:48:47.700+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:48:47.968+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to 2024-07-14 00:00:00+00:00, run_after=2024-07-15 00:00:00+00:00
[2024-07-14T04:48:48.294+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:48:48.515+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.best_employee_run, run_id=scheduled__2024-07-08T00:00:00+00:00, execution_date=20240708T000000, start_date=20240714T044746, end_date=20240714T044848
[2024-07-14T04:48:48.766+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:48:48.938+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:48:48.947+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
