[2024-07-14T04:45:21.305+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:45:21.475+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.gross_revenue_run scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-07-14T04:45:21.597+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.gross_revenue_run scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-07-14T04:45:21.599+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:45:22.229+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.gross_revenue_run> on 2024-07-05 00:00:00+00:00
[2024-07-14T04:45:22.267+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=21296) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:45:22.284+0000] {standard_task_runner.py:63} INFO - Started process 21328 to run task
[2024-07-14T04:45:22.289+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.gross_revenue_run', 'scheduled__2024-07-05T00:00:00+00:00', '--job-id', '1597', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpuoaypl7c']
[2024-07-14T04:45:22.315+0000] {standard_task_runner.py:91} INFO - Job 1597: Subtask transform.gross_revenue_run
[2024-07-14T04:45:22.413+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:45:22.584+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.gross_revenue_run scheduled__2024-07-05T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:45:23.024+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.gross_revenue_run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-05T00:00:00+00:00'
[2024-07-14T04:45:23.027+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:45:23.031+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:45:23.045+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp2b3_ofly from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:45:23.073+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:45:23.374+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:45:23.378+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:45:23.393+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:45:23.425+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:45:23.446+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp2b3_ofly', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp2b3_ofly
[2024-07-14T04:45:23.476+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:45:23.480+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp2b3_ofly', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:45:23.583+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:45:40.177+0000] {subprocess.py:94} INFO - [0m04:45:40  Running with dbt=1.8.3
[2024-07-14T04:45:41.895+0000] {subprocess.py:94} INFO - [0m04:45:41  Updating lock file in file path: /tmp/tmp2b3_ofly/package-lock.yml
[2024-07-14T04:45:41.920+0000] {subprocess.py:94} INFO - [0m04:45:41  Installing dbt-labs/dbt_utils
[2024-07-14T04:45:43.215+0000] {subprocess.py:94} INFO - [0m04:45:43  Installed from version 0.8.6
[2024-07-14T04:45:43.233+0000] {subprocess.py:94} INFO - [0m04:45:43  Updated version available: 1.2.0
[2024-07-14T04:45:43.239+0000] {subprocess.py:94} INFO - [0m04:45:43
[2024-07-14T04:45:43.243+0000] {subprocess.py:94} INFO - [0m04:45:43  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:45:43.245+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:45:45.246+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:45:45.248+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:45:45.252+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'gross_revenue', '--project-dir', '/tmp/tmp2b3_ofly', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp2b3_ofly
[2024-07-14T04:45:45.255+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:45:45.258+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'gross_revenue', '--project-dir', '/tmp/tmp2b3_ofly', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:45:45.322+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:46:00.827+0000] {subprocess.py:94} INFO - [0m04:46:00  Running with dbt=1.8.3
[2024-07-14T04:46:05.096+0000] {subprocess.py:94} INFO - [0m04:46:05  Registered adapter: snowflake=1.8.3
[2024-07-14T04:46:12.904+0000] {subprocess.py:94} INFO - [0m04:46:12  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:46:13.004+0000] {subprocess.py:94} INFO - [0m04:46:13
[2024-07-14T04:46:21.807+0000] {subprocess.py:94} INFO - [0m04:46:21  Concurrency: 1 threads (target='dev')
[2024-07-14T04:46:21.809+0000] {subprocess.py:94} INFO - [0m04:46:21
[2024-07-14T04:46:21.951+0000] {subprocess.py:94} INFO - [0m04:46:21  1 of 1 START sql table model dm.gross_revenue .................................. [RUN]
[2024-07-14T04:46:25.276+0000] {subprocess.py:94} INFO - [0m04:46:25  1 of 1 OK created sql table model dm.gross_revenue ............................. [[32mSUCCESS 1[0m in 3.31s]
[2024-07-14T04:46:25.313+0000] {subprocess.py:94} INFO - [0m04:46:25
[2024-07-14T04:46:25.317+0000] {subprocess.py:94} INFO - [0m04:46:25  Finished running 1 table model in 0 hours 0 minutes and 12.30 seconds (12.30s).
[2024-07-14T04:46:25.954+0000] {subprocess.py:94} INFO - [0m04:46:25
[2024-07-14T04:46:25.958+0000] {subprocess.py:94} INFO - [0m04:46:25  [32mCompleted successfully[0m
[2024-07-14T04:46:25.969+0000] {subprocess.py:94} INFO - [0m04:46:25
[2024-07-14T04:46:25.986+0000] {subprocess.py:94} INFO - [0m04:46:25  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:46:29.658+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:46:29.662+0000] {local.py:254} INFO - [0m04:46:25  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:46:30.937+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:46:30.951+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:46:30.974+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_products', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_suppliers', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.fact_order_details', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.fact_orders', extra=None)]
[2024-07-14T04:46:31.001+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dm.gross_revenue', extra=None)]
[2024-07-14T04:46:31.011+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:46:31.387+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to 2024-07-14 00:00:00+00:00, run_after=2024-07-15 00:00:00+00:00
[2024-07-14T04:46:31.518+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/datasets/manager.py:53 SAWarning: DELETE statement on table 'task_outlet_dataset_reference' expected to delete 1 row(s); 0 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
[2024-07-14T04:46:31.695+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:46:31.917+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.gross_revenue_run, run_id=scheduled__2024-07-05T00:00:00+00:00, execution_date=20240705T000000, start_date=20240714T044521, end_date=20240714T044631
[2024-07-14T04:46:32.115+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:46:32.344+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:46:32.380+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
