[2024-07-14T04:10:40.393+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:10:40.511+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_employees.run scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-07-14T04:10:40.697+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_employees.run scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-07-14T04:10:40.703+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:10:40.838+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.dim_employees.run> on 2024-06-29 00:00:00+00:00
[2024-07-14T04:10:40.881+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=14031) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:10:40.885+0000] {standard_task_runner.py:63} INFO - Started process 14056 to run task
[2024-07-14T04:10:40.886+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.dim_employees.run', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '1147', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmphrgofwuc']
[2024-07-14T04:10:40.897+0000] {standard_task_runner.py:91} INFO - Job 1147: Subtask transform.dim_employees.run
[2024-07-14T04:10:41.036+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:10:41.255+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.dim_employees.run scheduled__2024-06-29T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:10:41.893+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.dim_employees.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T00:00:00+00:00'
[2024-07-14T04:10:41.903+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:10:41.918+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:10:41.922+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpohxt50ow from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:10:41.938+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:10:42.241+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:10:42.243+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:10:42.245+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:10:42.308+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:10:42.316+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpohxt50ow', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpohxt50ow
[2024-07-14T04:10:42.347+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:10:42.360+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpohxt50ow', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:10:42.482+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:11:00.181+0000] {subprocess.py:94} INFO - [0m04:11:00  Running with dbt=1.8.3
[2024-07-14T04:11:01.328+0000] {subprocess.py:94} INFO - [0m04:11:01  Updating lock file in file path: /tmp/tmpohxt50ow/package-lock.yml
[2024-07-14T04:11:01.354+0000] {subprocess.py:94} INFO - [0m04:11:01  Installing dbt-labs/dbt_utils
[2024-07-14T04:11:02.435+0000] {subprocess.py:94} INFO - [0m04:11:02  Installed from version 0.8.6
[2024-07-14T04:11:02.445+0000] {subprocess.py:94} INFO - [0m04:11:02  Updated version available: 1.2.0
[2024-07-14T04:11:02.464+0000] {subprocess.py:94} INFO - [0m04:11:02
[2024-07-14T04:11:02.469+0000] {subprocess.py:94} INFO - [0m04:11:02  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:11:02.473+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:11:04.565+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:11:04.599+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:11:04.606+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'dim_employees', '--project-dir', '/tmp/tmpohxt50ow', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpohxt50ow
[2024-07-14T04:11:04.611+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:11:04.615+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'dim_employees', '--project-dir', '/tmp/tmpohxt50ow', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:11:04.731+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:11:22.026+0000] {subprocess.py:94} INFO - [0m04:11:22  Running with dbt=1.8.3
[2024-07-14T04:11:26.026+0000] {subprocess.py:94} INFO - [0m04:11:26  Registered adapter: snowflake=1.8.3
[2024-07-14T04:11:30.330+0000] {subprocess.py:94} INFO - [0m04:11:30  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:11:30.342+0000] {subprocess.py:94} INFO - [0m04:11:30
[2024-07-14T04:11:37.747+0000] {subprocess.py:94} INFO - [0m04:11:37  Concurrency: 1 threads (target='dev')
[2024-07-14T04:11:37.765+0000] {subprocess.py:94} INFO - [0m04:11:37
[2024-07-14T04:11:37.849+0000] {subprocess.py:94} INFO - [0m04:11:37  1 of 1 START sql table model dwh.dim_employees ................................. [RUN]
[2024-07-14T04:11:40.487+0000] {subprocess.py:94} INFO - [0m04:11:40  1 of 1 OK created sql table model dwh.dim_employees ............................ [[32mSUCCESS 1[0m in 2.62s]
[2024-07-14T04:11:40.503+0000] {subprocess.py:94} INFO - [0m04:11:40
[2024-07-14T04:11:40.507+0000] {subprocess.py:94} INFO - [0m04:11:40  Finished running 1 table model in 0 hours 0 minutes and 10.16 seconds (10.16s).
[2024-07-14T04:11:40.986+0000] {subprocess.py:94} INFO - [0m04:11:40
[2024-07-14T04:11:40.989+0000] {subprocess.py:94} INFO - [0m04:11:40  [32mCompleted successfully[0m
[2024-07-14T04:11:40.991+0000] {subprocess.py:94} INFO - [0m04:11:40
[2024-07-14T04:11:40.993+0000] {subprocess.py:94} INFO - [0m04:11:40  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:11:43.619+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:11:43.621+0000] {local.py:254} INFO - [0m04:11:40  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:11:45.002+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:11:45.017+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:11:45.046+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_employees', extra=None)]
[2024-07-14T04:11:45.058+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_employees', extra=None)]
[2024-07-14T04:11:45.067+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:11:45.669+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:11:45.931+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.dim_employees.run, run_id=scheduled__2024-06-29T00:00:00+00:00, execution_date=20240629T000000, start_date=20240714T041040, end_date=20240714T041145
[2024-07-14T04:11:46.106+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:11:46.205+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
