[2024-07-09T20:27:35.580+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T20:27:35.779+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_customers.run manual__2024-07-09T20:27:28.353351+00:00 [queued]>
[2024-07-09T20:27:35.920+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_customers.run manual__2024-07-09T20:27:28.353351+00:00 [queued]>
[2024-07-09T20:27:35.927+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-09T20:27:36.551+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_customers.run> on 2024-07-09 20:27:28.353351+00:00
[2024-07-09T20:27:36.630+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8163) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-09T20:27:36.633+0000] {standard_task_runner.py:63} INFO - Started process 8205 to run task
[2024-07-09T20:27:36.632+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_customers.run', 'manual__2024-07-09T20:27:28.353351+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpcbh8by3w']
[2024-07-09T20:27:36.663+0000] {standard_task_runner.py:91} INFO - Job 117: Subtask transform.raw_customers.run
[2024-07-09T20:27:36.809+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-09T20:27:37.107+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_customers.run manual__2024-07-09T20:27:28.353351+00:00 [running]> on host airflow-scheduler
[2024-07-09T20:27:37.812+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_customers.run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T20:27:28.353351+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T20:27:28.353351+00:00'
[2024-07-09T20:27:37.819+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T20:27:37.826+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-09T20:27:37.838+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpw3ymdx43 from /opt/airflow/dags/dbt/dbt_project
[2024-07-09T20:27:37.873+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /opt/airflow/dags/dbt/dbt_project/target/partial_parse.msgpack
[2024-07-09T20:27:38.127+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T20:27:38.194+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/base.py", line 270, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 489, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 307, in run_command
    with self.profile_config.ensure_profile() as profile_values:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 295, in ensure_profile
    env_vars = self.profile_mapping.env_vars
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 224, in env_vars
    value = self.get_dbt_value(field)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 295, in get_dbt_value
    value = self._get_airflow_conn_field(airflow_field)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 272, in _get_airflow_conn_field
    value = getattr(self.conn, airflow_field, None)
                    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/snowflake/user_pass.py", line 65, in conn
    conn = super().conn
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 146, in conn
    conn = BaseHook.get_connection(self.conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2024-07-09T20:27:38.233+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ELT-PROJECT, task_id=transform.raw_customers.run, run_id=manual__2024-07-09T20:27:28.353351+00:00, execution_date=20240709T202728, start_date=20240709T202735, end_date=20240709T202738
[2024-07-09T20:27:38.480+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 117 for task transform.raw_customers.run (The conn_id `snow_conn` isn't defined; 8205)
[2024-07-09T20:27:38.525+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-09T20:27:38.665+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T20:27:38.672+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
