[2024-07-14T04:11:52.054+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:11:52.202+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_employees.run scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-14T04:11:52.272+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_employees.run scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-14T04:11:52.279+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:11:52.395+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.dim_employees.run> on 2024-07-02 00:00:00+00:00
[2024-07-14T04:11:52.415+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=14312) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:11:52.431+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.dim_employees.run', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '1162', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp9400ie79']
[2024-07-14T04:11:52.440+0000] {standard_task_runner.py:63} INFO - Started process 14331 to run task
[2024-07-14T04:11:52.445+0000] {standard_task_runner.py:91} INFO - Job 1162: Subtask transform.dim_employees.run
[2024-07-14T04:11:52.546+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:11:52.806+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.dim_employees.run scheduled__2024-07-02T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:11:53.512+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.dim_employees.run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-14T04:11:53.517+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:11:53.522+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:11:53.527+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpvunua6va from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:11:53.547+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:11:53.749+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:11:53.755+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:11:53.762+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:11:53.775+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:11:53.785+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpvunua6va', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpvunua6va
[2024-07-14T04:11:53.799+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:11:53.808+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpvunua6va', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:11:53.919+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:12:09.772+0000] {subprocess.py:94} INFO - [0m04:12:09  Running with dbt=1.8.3
[2024-07-14T04:12:11.460+0000] {subprocess.py:94} INFO - [0m04:12:11  Updating lock file in file path: /tmp/tmpvunua6va/package-lock.yml
[2024-07-14T04:12:11.526+0000] {subprocess.py:94} INFO - [0m04:12:11  Installing dbt-labs/dbt_utils
[2024-07-14T04:12:12.298+0000] {subprocess.py:94} INFO - [0m04:12:12  Installed from version 0.8.6
[2024-07-14T04:12:12.315+0000] {subprocess.py:94} INFO - [0m04:12:12  Updated version available: 1.2.0
[2024-07-14T04:12:12.322+0000] {subprocess.py:94} INFO - [0m04:12:12
[2024-07-14T04:12:12.328+0000] {subprocess.py:94} INFO - [0m04:12:12  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:12:12.330+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:12:14.280+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:12:14.283+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:12:14.287+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'dim_employees', '--project-dir', '/tmp/tmpvunua6va', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpvunua6va
[2024-07-14T04:12:14.291+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:12:14.293+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'dim_employees', '--project-dir', '/tmp/tmpvunua6va', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:12:14.374+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:12:29.293+0000] {subprocess.py:94} INFO - [0m04:12:29  Running with dbt=1.8.3
[2024-07-14T04:12:34.131+0000] {subprocess.py:94} INFO - [0m04:12:34  Registered adapter: snowflake=1.8.3
[2024-07-14T04:12:39.279+0000] {subprocess.py:94} INFO - [0m04:12:39  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:12:39.284+0000] {subprocess.py:94} INFO - [0m04:12:39
[2024-07-14T04:12:47.510+0000] {subprocess.py:94} INFO - [0m04:12:47  Concurrency: 1 threads (target='dev')
[2024-07-14T04:12:47.514+0000] {subprocess.py:94} INFO - [0m04:12:47
[2024-07-14T04:12:47.601+0000] {subprocess.py:94} INFO - [0m04:12:47  1 of 1 START sql table model dwh.dim_employees ................................. [RUN]
[2024-07-14T04:12:50.283+0000] {subprocess.py:94} INFO - [0m04:12:50  1 of 1 OK created sql table model dwh.dim_employees ............................ [[32mSUCCESS 1[0m in 2.67s]
[2024-07-14T04:12:50.312+0000] {subprocess.py:94} INFO - [0m04:12:50
[2024-07-14T04:12:50.317+0000] {subprocess.py:94} INFO - [0m04:12:50  Finished running 1 table model in 0 hours 0 minutes and 11.02 seconds (11.02s).
[2024-07-14T04:12:50.769+0000] {subprocess.py:94} INFO - [0m04:12:50
[2024-07-14T04:12:50.772+0000] {subprocess.py:94} INFO - [0m04:12:50  [32mCompleted successfully[0m
[2024-07-14T04:12:50.776+0000] {subprocess.py:94} INFO - [0m04:12:50
[2024-07-14T04:12:50.785+0000] {subprocess.py:94} INFO - [0m04:12:50  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:12:53.819+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:12:53.822+0000] {local.py:254} INFO - [0m04:12:50  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:12:55.223+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:12:55.230+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:12:55.257+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_employees', extra=None)]
[2024-07-14T04:12:55.281+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_employees', extra=None)]
[2024-07-14T04:12:55.284+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:12:55.664+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:12:55.868+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.dim_employees.run, run_id=scheduled__2024-07-02T00:00:00+00:00, execution_date=20240702T000000, start_date=20240714T041152, end_date=20240714T041255
[2024-07-14T04:12:56.986+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:12:57.252+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:12:57.269+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
