[2024-07-14T04:33:05.966+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:33:06.264+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_customers.run scheduled__2024-06-28T00:00:00+00:00 [queued]>
[2024-07-14T04:33:06.336+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_customers.run scheduled__2024-06-28T00:00:00+00:00 [queued]>
[2024-07-14T04:33:06.344+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:33:06.427+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_customers.run> on 2024-06-28 00:00:00+00:00
[2024-07-14T04:33:06.464+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=18666) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:33:06.474+0000] {standard_task_runner.py:63} INFO - Started process 18710 to run task
[2024-07-14T04:33:06.514+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_customers.run', 'scheduled__2024-06-28T00:00:00+00:00', '--job-id', '1428', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpoh98rnv8']
[2024-07-14T04:33:06.551+0000] {standard_task_runner.py:91} INFO - Job 1428: Subtask transform.raw_customers.run
[2024-07-14T04:33:06.866+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:33:07.166+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_customers.run scheduled__2024-06-28T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:33:07.688+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_customers.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-28T00:00:00+00:00'
[2024-07-14T04:33:07.694+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:33:07.701+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:33:07.708+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmptjo0b6kd from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:33:07.735+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:33:07.932+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:33:07.938+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:33:07.952+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:33:07.974+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:33:07.989+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmptjo0b6kd', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmptjo0b6kd
[2024-07-14T04:33:07.997+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:33:08.011+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmptjo0b6kd', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:33:08.088+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:33:23.973+0000] {subprocess.py:94} INFO - [0m04:33:23  Running with dbt=1.8.3
[2024-07-14T04:33:25.508+0000] {subprocess.py:94} INFO - [0m04:33:25  Updating lock file in file path: /tmp/tmptjo0b6kd/package-lock.yml
[2024-07-14T04:33:25.551+0000] {subprocess.py:94} INFO - [0m04:33:25  Installing dbt-labs/dbt_utils
[2024-07-14T04:33:26.756+0000] {subprocess.py:94} INFO - [0m04:33:26  Installed from version 0.8.6
[2024-07-14T04:33:26.770+0000] {subprocess.py:94} INFO - [0m04:33:26  Updated version available: 1.2.0
[2024-07-14T04:33:26.814+0000] {subprocess.py:94} INFO - [0m04:33:26
[2024-07-14T04:33:26.817+0000] {subprocess.py:94} INFO - [0m04:33:26  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:33:26.819+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:33:29.370+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:33:29.375+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:33:29.377+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_customers', '--project-dir', '/tmp/tmptjo0b6kd', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmptjo0b6kd
[2024-07-14T04:33:29.380+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:33:29.382+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_customers', '--project-dir', '/tmp/tmptjo0b6kd', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:33:29.473+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:33:46.762+0000] {subprocess.py:94} INFO - [0m04:33:46  Running with dbt=1.8.3
[2024-07-14T04:33:50.585+0000] {subprocess.py:94} INFO - [0m04:33:50  Registered adapter: snowflake=1.8.3
[2024-07-14T04:33:55.830+0000] {subprocess.py:94} INFO - [0m04:33:55  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:33:55.843+0000] {subprocess.py:94} INFO - [0m04:33:55
[2024-07-14T04:34:03.971+0000] {subprocess.py:94} INFO - [0m04:34:03  Concurrency: 1 threads (target='dev')
[2024-07-14T04:34:04.002+0000] {subprocess.py:94} INFO - [0m04:34:03
[2024-07-14T04:34:04.091+0000] {subprocess.py:94} INFO - [0m04:34:04  1 of 1 START sql table model raw.raw_customers ................................. [RUN]
[2024-07-14T04:34:07.750+0000] {subprocess.py:94} INFO - [0m04:34:07  1 of 1 OK created sql table model raw.raw_customers ............................ [[32mSUCCESS 1[0m in 3.61s]
[2024-07-14T04:34:07.781+0000] {subprocess.py:94} INFO - [0m04:34:07
[2024-07-14T04:34:07.785+0000] {subprocess.py:94} INFO - [0m04:34:07  Finished running 1 table model in 0 hours 0 minutes and 11.93 seconds (11.93s).
[2024-07-14T04:34:08.533+0000] {subprocess.py:94} INFO - [0m04:34:08
[2024-07-14T04:34:08.537+0000] {subprocess.py:94} INFO - [0m04:34:08  [32mCompleted successfully[0m
[2024-07-14T04:34:08.540+0000] {subprocess.py:94} INFO - [0m04:34:08
[2024-07-14T04:34:08.550+0000] {subprocess.py:94} INFO - [0m04:34:08  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:34:12.439+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:34:12.442+0000] {local.py:254} INFO - [0m04:34:08  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:34:13.983+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:34:13.995+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:34:14.054+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.PUBLIC.customers', extra=None)]
[2024-07-14T04:34:14.065+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_customers', extra=None)]
[2024-07-14T04:34:14.099+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:34:14.538+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:34:14.787+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_customers.run, run_id=scheduled__2024-06-28T00:00:00+00:00, execution_date=20240628T000000, start_date=20240714T043306, end_date=20240714T043414
[2024-07-14T04:34:15.939+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:34:16.072+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:34:16.085+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
