[2024-07-14T04:25:54.178+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:25:54.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.fact_orders.run scheduled__2024-07-12T00:00:00+00:00 [queued]>
[2024-07-14T04:25:54.432+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.fact_orders.run scheduled__2024-07-12T00:00:00+00:00 [queued]>
[2024-07-14T04:25:54.433+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:25:55.873+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.fact_orders.run> on 2024-07-12 00:00:00+00:00
[2024-07-14T04:25:55.926+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=17244) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:25:55.949+0000] {standard_task_runner.py:63} INFO - Started process 17295 to run task
[2024-07-14T04:25:55.947+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.fact_orders.run', 'scheduled__2024-07-12T00:00:00+00:00', '--job-id', '1342', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp23cmehb0']
[2024-07-14T04:25:55.966+0000] {standard_task_runner.py:91} INFO - Job 1342: Subtask transform.fact_orders.run
[2024-07-14T04:25:56.074+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:25:56.438+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.fact_orders.run scheduled__2024-07-12T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:25:57.000+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.fact_orders.run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-12T00:00:00+00:00'
[2024-07-14T04:25:57.009+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:25:57.029+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:25:57.034+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpyzakfc4q from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:25:57.063+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:25:57.221+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:25:57.223+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:25:57.225+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:25:57.231+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:25:57.236+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpyzakfc4q', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpyzakfc4q
[2024-07-14T04:25:57.244+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:25:57.247+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpyzakfc4q', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:25:57.317+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:26:14.333+0000] {subprocess.py:94} INFO - [0m04:26:14  Running with dbt=1.8.3
[2024-07-14T04:26:15.727+0000] {subprocess.py:94} INFO - [0m04:26:15  Updating lock file in file path: /tmp/tmpyzakfc4q/package-lock.yml
[2024-07-14T04:26:15.805+0000] {subprocess.py:94} INFO - [0m04:26:15  Installing dbt-labs/dbt_utils
[2024-07-14T04:26:17.102+0000] {subprocess.py:94} INFO - [0m04:26:17  Installed from version 0.8.6
[2024-07-14T04:26:17.108+0000] {subprocess.py:94} INFO - [0m04:26:17  Updated version available: 1.2.0
[2024-07-14T04:26:17.128+0000] {subprocess.py:94} INFO - [0m04:26:17
[2024-07-14T04:26:17.151+0000] {subprocess.py:94} INFO - [0m04:26:17  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:26:17.154+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:26:20.359+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:26:20.363+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:26:20.369+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'fact_orders', '--project-dir', '/tmp/tmpyzakfc4q', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpyzakfc4q
[2024-07-14T04:26:20.377+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:26:20.380+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'fact_orders', '--project-dir', '/tmp/tmpyzakfc4q', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:26:20.525+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:26:37.560+0000] {subprocess.py:94} INFO - [0m04:26:37  Running with dbt=1.8.3
[2024-07-14T04:26:42.379+0000] {subprocess.py:94} INFO - [0m04:26:42  Registered adapter: snowflake=1.8.3
[2024-07-14T04:26:47.289+0000] {subprocess.py:94} INFO - [0m04:26:47  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:26:47.317+0000] {subprocess.py:94} INFO - [0m04:26:47
[2024-07-14T04:26:59.370+0000] {subprocess.py:94} INFO - [0m04:26:59  Concurrency: 1 threads (target='dev')
[2024-07-14T04:26:59.384+0000] {subprocess.py:94} INFO - [0m04:26:59
[2024-07-14T04:26:59.486+0000] {subprocess.py:94} INFO - [0m04:26:59  1 of 1 START sql table model dwh.fact_orders ................................... [RUN]
[2024-07-14T04:27:02.634+0000] {subprocess.py:94} INFO - [0m04:27:02  1 of 1 OK created sql table model dwh.fact_orders .............................. [[32mSUCCESS 1[0m in 3.13s]
[2024-07-14T04:27:02.661+0000] {subprocess.py:94} INFO - [0m04:27:02
[2024-07-14T04:27:02.674+0000] {subprocess.py:94} INFO - [0m04:27:02  Finished running 1 table model in 0 hours 0 minutes and 15.33 seconds (15.33s).
[2024-07-14T04:27:03.334+0000] {subprocess.py:94} INFO - [0m04:27:03
[2024-07-14T04:27:03.348+0000] {subprocess.py:94} INFO - [0m04:27:03  [32mCompleted successfully[0m
[2024-07-14T04:27:03.350+0000] {subprocess.py:94} INFO - [0m04:27:03
[2024-07-14T04:27:03.372+0000] {subprocess.py:94} INFO - [0m04:27:03  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:27:06.142+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:27:06.144+0000] {local.py:254} INFO - [0m04:27:03  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:27:07.098+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:27:07.100+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:27:07.122+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_employees', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_orders', extra=None)]
[2024-07-14T04:27:07.138+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.fact_orders', extra=None)]
[2024-07-14T04:27:07.141+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:27:07.705+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:27:08.136+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.fact_orders.run, run_id=scheduled__2024-07-12T00:00:00+00:00, execution_date=20240712T000000, start_date=20240714T042554, end_date=20240714T042708
[2024-07-14T04:27:08.457+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:27:08.640+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:27:08.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
