[2024-07-14T04:03:17.501+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:03:17.748+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_suppliers.run scheduled__2024-06-30T00:00:00+00:00 [queued]>
[2024-07-14T04:03:17.852+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_suppliers.run scheduled__2024-06-30T00:00:00+00:00 [queued]>
[2024-07-14T04:03:17.853+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:03:19.269+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_suppliers.run> on 2024-06-30 00:00:00+00:00
[2024-07-14T04:03:19.328+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12390) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:03:19.333+0000] {standard_task_runner.py:63} INFO - Started process 12436 to run task
[2024-07-14T04:03:19.328+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_suppliers.run', 'scheduled__2024-06-30T00:00:00+00:00', '--job-id', '1038', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpqs2c84mx']
[2024-07-14T04:03:19.356+0000] {standard_task_runner.py:91} INFO - Job 1038: Subtask transform.raw_suppliers.run
[2024-07-14T04:03:19.512+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:03:19.783+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_suppliers.run scheduled__2024-06-30T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:03:20.270+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_suppliers.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T00:00:00+00:00'
[2024-07-14T04:03:20.274+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:03:20.280+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:03:20.286+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp_5tj3cuk from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:03:20.318+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:03:20.512+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:03:20.516+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:03:20.518+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:03:20.523+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:03:20.527+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp_5tj3cuk', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp_5tj3cuk
[2024-07-14T04:03:20.531+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:03:20.534+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp_5tj3cuk', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:03:20.613+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:03:38.427+0000] {subprocess.py:94} INFO - [0m04:03:38  Running with dbt=1.8.3
[2024-07-14T04:03:39.955+0000] {subprocess.py:94} INFO - [0m04:03:39  Updating lock file in file path: /tmp/tmp_5tj3cuk/package-lock.yml
[2024-07-14T04:03:40.017+0000] {subprocess.py:94} INFO - [0m04:03:40  Installing dbt-labs/dbt_utils
[2024-07-14T04:03:40.784+0000] {subprocess.py:94} INFO - [0m04:03:40  Installed from version 0.8.6
[2024-07-14T04:03:40.804+0000] {subprocess.py:94} INFO - [0m04:03:40  Updated version available: 1.2.0
[2024-07-14T04:03:40.809+0000] {subprocess.py:94} INFO - [0m04:03:40
[2024-07-14T04:03:40.812+0000] {subprocess.py:94} INFO - [0m04:03:40  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:03:40.814+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:03:42.823+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:03:42.826+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:03:42.830+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_suppliers', '--project-dir', '/tmp/tmp_5tj3cuk', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp_5tj3cuk
[2024-07-14T04:03:42.833+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:03:42.836+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_suppliers', '--project-dir', '/tmp/tmp_5tj3cuk', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:03:42.947+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:03:59.289+0000] {subprocess.py:94} INFO - [0m04:03:59  Running with dbt=1.8.3
[2024-07-14T04:04:04.475+0000] {subprocess.py:94} INFO - [0m04:04:04  Registered adapter: snowflake=1.8.3
[2024-07-14T04:04:09.405+0000] {subprocess.py:94} INFO - [0m04:04:09  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:04:09.420+0000] {subprocess.py:94} INFO - [0m04:04:09
[2024-07-14T04:04:18.084+0000] {subprocess.py:94} INFO - [0m04:04:18  Concurrency: 1 threads (target='dev')
[2024-07-14T04:04:18.087+0000] {subprocess.py:94} INFO - [0m04:04:18
[2024-07-14T04:04:18.115+0000] {subprocess.py:94} INFO - [0m04:04:18  1 of 1 START sql table model raw.raw_suppliers ................................. [RUN]
[2024-07-14T04:04:20.679+0000] {subprocess.py:94} INFO - [0m04:04:20  1 of 1 OK created sql table model raw.raw_suppliers ............................ [[32mSUCCESS 1[0m in 2.56s]
[2024-07-14T04:04:20.696+0000] {subprocess.py:94} INFO - [0m04:04:20
[2024-07-14T04:04:20.699+0000] {subprocess.py:94} INFO - [0m04:04:20  Finished running 1 table model in 0 hours 0 minutes and 11.27 seconds (11.27s).
[2024-07-14T04:04:21.123+0000] {subprocess.py:94} INFO - [0m04:04:21
[2024-07-14T04:04:21.127+0000] {subprocess.py:94} INFO - [0m04:04:21  [32mCompleted successfully[0m
[2024-07-14T04:04:21.135+0000] {subprocess.py:94} INFO - [0m04:04:21
[2024-07-14T04:04:21.142+0000] {subprocess.py:94} INFO - [0m04:04:21  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:04:23.190+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:04:23.193+0000] {local.py:254} INFO - [0m04:04:21  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:04:23.935+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:04:23.937+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:04:23.956+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.PUBLIC.suppliers', extra=None)]
[2024-07-14T04:04:23.958+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_suppliers', extra=None)]
[2024-07-14T04:04:23.961+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:04:24.399+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:04:24.603+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_suppliers.run, run_id=scheduled__2024-06-30T00:00:00+00:00, execution_date=20240630T000000, start_date=20240714T040317, end_date=20240714T040424
[2024-07-14T04:04:26.059+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:04:26.290+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:04:26.306+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
