[2024-07-14T04:18:58.027+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:18:58.214+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_orders.test scheduled__2024-07-03T00:00:00+00:00 [queued]>
[2024-07-14T04:18:58.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_orders.test scheduled__2024-07-03T00:00:00+00:00 [queued]>
[2024-07-14T04:18:58.337+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:18:58.462+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_orders.test> on 2024-07-03 00:00:00+00:00
[2024-07-14T04:18:58.499+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=15775) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:18:58.515+0000] {standard_task_runner.py:63} INFO - Started process 15795 to run task
[2024-07-14T04:18:58.495+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_orders.test', 'scheduled__2024-07-03T00:00:00+00:00', '--job-id', '1252', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp2_lp_qnh']
[2024-07-14T04:18:58.531+0000] {standard_task_runner.py:91} INFO - Job 1252: Subtask transform.raw_orders.test
[2024-07-14T04:18:58.638+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:18:58.811+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_orders.test scheduled__2024-07-03T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:18:59.508+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_orders.test' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-03T00:00:00+00:00'
[2024-07-14T04:18:59.520+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:18:59.536+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:18:59.561+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp2mviy_ae from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:18:59.618+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:18:59.974+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:18:59.991+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:18:59.993+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:18:59.999+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:19:00.023+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp2mviy_ae', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp2mviy_ae
[2024-07-14T04:19:00.039+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:19:00.052+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp2mviy_ae', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:19:00.243+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:19:17.194+0000] {subprocess.py:94} INFO - [0m04:19:17  Running with dbt=1.8.3
[2024-07-14T04:19:19.635+0000] {subprocess.py:94} INFO - [0m04:19:19  Updating lock file in file path: /tmp/tmp2mviy_ae/package-lock.yml
[2024-07-14T04:19:19.728+0000] {subprocess.py:94} INFO - [0m04:19:19  Installing dbt-labs/dbt_utils
[2024-07-14T04:19:21.038+0000] {subprocess.py:94} INFO - [0m04:19:21  Installed from version 0.8.6
[2024-07-14T04:19:21.045+0000] {subprocess.py:94} INFO - [0m04:19:21  Updated version available: 1.2.0
[2024-07-14T04:19:21.048+0000] {subprocess.py:94} INFO - [0m04:19:21
[2024-07-14T04:19:21.052+0000] {subprocess.py:94} INFO - [0m04:19:21  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:19:21.054+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:19:22.832+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:19:22.834+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:19:22.837+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_orders', '--project-dir', '/tmp/tmp2mviy_ae', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp2mviy_ae
[2024-07-14T04:19:22.839+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:19:22.843+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_orders', '--project-dir', '/tmp/tmp2mviy_ae', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:19:22.876+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:19:33.943+0000] {subprocess.py:94} INFO - [0m04:19:33  Running with dbt=1.8.3
[2024-07-14T04:19:37.498+0000] {subprocess.py:94} INFO - [0m04:19:37  Registered adapter: snowflake=1.8.3
[2024-07-14T04:19:43.253+0000] {subprocess.py:94} INFO - [0m04:19:43  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:19:43.266+0000] {subprocess.py:94} INFO - [0m04:19:43
[2024-07-14T04:19:49.739+0000] {subprocess.py:94} INFO - [0m04:19:49  Concurrency: 1 threads (target='dev')
[2024-07-14T04:19:49.808+0000] {subprocess.py:94} INFO - [0m04:19:49
[2024-07-14T04:19:50.044+0000] {subprocess.py:94} INFO - [0m04:19:50  1 of 1 START test not_null_raw_orders_ORDERID .................................. [RUN]
[2024-07-14T04:19:52.932+0000] {subprocess.py:94} INFO - [0m04:19:52  1 of 1 PASS not_null_raw_orders_ORDERID ........................................ [[32mPASS[0m in 2.88s]
[2024-07-14T04:19:52.959+0000] {subprocess.py:94} INFO - [0m04:19:52
[2024-07-14T04:19:52.961+0000] {subprocess.py:94} INFO - [0m04:19:52  Finished running 1 test in 0 hours 0 minutes and 9.66 seconds (9.66s).
[2024-07-14T04:19:53.561+0000] {subprocess.py:94} INFO - [0m04:19:53
[2024-07-14T04:19:53.564+0000] {subprocess.py:94} INFO - [0m04:19:53  [32mCompleted successfully[0m
[2024-07-14T04:19:53.567+0000] {subprocess.py:94} INFO - [0m04:19:53
[2024-07-14T04:19:53.571+0000] {subprocess.py:94} INFO - [0m04:19:53  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:20:00.521+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:20:00.525+0000] {local.py:254} INFO - [0m04:19:53  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:20:02.173+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:20:02.204+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:20:02.291+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_orders', extra=None)]
[2024-07-14T04:20:02.307+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T04:20:02.332+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:20:02.767+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:20:02.911+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_orders.test, run_id=scheduled__2024-07-03T00:00:00+00:00, execution_date=20240703T000000, start_date=20240714T041858, end_date=20240714T042002
[2024-07-14T04:20:03.567+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:20:04.017+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:20:04.037+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
